# Generated by Django 4.2.4 on 2023-10-22 16:51
import random

from django.db import migrations


def add_barcode(app, schema_editor):
    Product = app.get_model("main_app", "Product")
    products = Product.objects.all()
    all_barcodes = random.sample(
        range(100000000, 999999999),
        len(products)
    )
    print(all_barcodes)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_product_created_on_and_more'),
    ]

    operations = [migrations.RunPython(add_barcode)
    ]
