# Generated by Django 4.2.4 on 2023-10-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.URLField(blank=True, default='http://default.url/image.png'),
        ),
    ]
