# Generated by Django 4.2.4 on 2023-10-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_employee_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, choices=[('jan', 'January'), ('feb', 'February')]),
        ),
    ]
