# Generated by Django 4.2.4 on 2023-10-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_employee_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('employees_count', models.IntegerField(default=1, verbose_name='Employees Count')),
                ('location', models.CharField(blank=True, choices=[('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Burgas', 'Burgas'), ('Varna', 'Varna')], max_length=20, null=True)),
                ('last_edited_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=40, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, choices=[('jan', 'January'), ('feb', 'February'), ('Mar', 'March')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_address',
            field=models.EmailField(editable=False, max_length=254, unique=True, verbose_name='email_address'),
        ),
    ]
