# Generated by Django 4.2.4 on 2023-10-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_department_remove_employee_name_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email_address',
            field=models.EmailField(editable=False, max_length=254, null=True, unique=True, verbose_name='email_address'),
        ),
    ]
