# Generated by Django 4.2.4 on 2023-10-31 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_employee_first_name_remove_employee_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, editable=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('duration_in_days', models.PositiveIntegerField(blank=True, verbose_name='Duration in Days')),
                ('estimated_hours', models.FloatField(blank=True, verbose_name='Estimated Hours')),
                ('start_date', models.DateField(blank=True, default=datetime.date(2023, 10, 31), verbose_name='Start Date')),
                ('last_edited_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
