# Generated by Django 4.2.7 on 2023-11-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChessPlayer',
        ),
        migrations.DeleteModel(
            name='Dungeon',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
